[GNSS-SDR]
GNSS-SDR.internal_fs_sps=10500000

SignalSource.implementation=Labsat_Signal_Source
SignalSource.filename=GPS_QZSS_L1CA_10p5m_180s_1bit.LS3W
SignalSource.selected_channel=1
SignalSource.item_type=gr_complex
SignalSource.sampling_frequency=10500000
SignalSource.samples=0
SignalSource.repeat=false
SignalSource.dump=false
SignalSource.enable_throttle_control=false

SignalConditioner.implementation=Signal_Conditioner
DataTypeAdapter.implementation=Pass_Through
DataTypeAdapter.item_type=gr_complex
InputFilter.implementation=Pass_Through
Resampler.implementation=Pass_Through

Channel.signal=J1
Channels.count=7
Channels.in_acquisition=7
Channels_J1.count=7

Acquisition_J1.implementation=QZSS_L1_PCPS_Acquisition
Acquisition_J1.item_type=gr_complex
Acquisition_J1.pfa=0.01
Acquisition_J1.doppler_max=10000
Acquisition_J1.doppler_step=250
Acquisition_J1.coherent_integration_time_ms=1
Acquisition_J1.max_dwells=2
Acquisition_J1.blocking=true
Acquisition_J1.dump=false

Tracking_J1.implementation=QZSS_L1_CA_DLL_PLL_Tracking
Tracking_J1.item_type=gr_complex
Tracking_J1.early_late_space_chips=0.5
Tracking_J1.pll_bw_hz=25.0
Tracking_J1.dll_bw_hz=3.0
Tracking_J1.enable_fll_pull_in=true
Tracking_J1.enable_fll_steady_state=false
Tracking_J1.dump=false

TelemetryDecoder_J1.implementation=QZSS_L1_Telemetry_Decoder
Observables.implementation=Hybrid_Observables
PVT.implementation=RTKLIB_PVT
PVT.positioning_mode=Single
PVT.navigation_system=16
PVT.elevation_mask=0
PVT.threshold_reject_gdop=9999
PVT.use_unhealthy_sats=true
PVT.output_rate_ms=100
PVT.display_rate_ms=500
PVT.flag_nmea_tty_port=false
PVT.flag_rtcm_server=false
PVT.flag_rtcm_tty_port=false
PVT.dump=false
PVT.nmea_output_file_enabled=false
